/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RssRouteImport } from './routes/rss'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as BylineSlugRouteImport } from './routes/byline.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as SubcategorySlugRouteImport } from './routes/subcategory.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BylineSlugRoute = BylineSlugRouteImport.update({
  id: '/byline/$slug',
  path: '/byline/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcategorySlugRoute = SubcategorySlugRouteImport.update({
  id: '/subcategory/$slug',
  path: '/subcategory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/rss': typeof RssRoute
  '/terms': typeof TermsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/byline/$slug': typeof BylineSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/subcategory/$slug': typeof SubcategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/rss': typeof RssRoute
  '/terms': typeof TermsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/byline/$slug': typeof BylineSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/subcategory/$slug': typeof SubcategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/rss': typeof RssRoute
  '/terms': typeof TermsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/byline/$slug': typeof BylineSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/subcategory/$slug': typeof SubcategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise'
    | '/careers'
    | '/contact'
    | '/news'
    | '/newsletter'
    | '/privacy'
    | '/rss'
    | '/terms'
    | '/article/$slug'
    | '/byline/$slug'
    | '/category/$slug'
    | '/subcategory/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/careers'
    | '/contact'
    | '/news'
    | '/newsletter'
    | '/privacy'
    | '/rss'
    | '/terms'
    | '/article/$slug'
    | '/byline/$slug'
    | '/category/$slug'
    | '/subcategory/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise'
    | '/careers'
    | '/contact'
    | '/news'
    | '/newsletter'
    | '/privacy'
    | '/rss'
    | '/terms'
    | '/article/$slug'
    | '/byline/$slug'
    | '/category/$slug'
    | '/subcategory/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  NewsletterRoute: typeof NewsletterRoute
  PrivacyRoute: typeof PrivacyRoute
  RssRoute: typeof RssRoute
  TermsRoute: typeof TermsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  BylineSlugRoute: typeof BylineSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  SubcategorySlugRoute: typeof SubcategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byline/$slug': {
      id: '/byline/$slug'
      path: '/byline/$slug'
      fullPath: '/byline/$slug'
      preLoaderRoute: typeof BylineSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcategory/$slug': {
      id: '/subcategory/$slug'
      path: '/subcategory/$slug'
      fullPath: '/subcategory/$slug'
      preLoaderRoute: typeof SubcategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  NewsletterRoute: NewsletterRoute,
  PrivacyRoute: PrivacyRoute,
  RssRoute: RssRoute,
  TermsRoute: TermsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  BylineSlugRoute: BylineSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  SubcategorySlugRoute: SubcategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
